from typing import Optional, Protocol

from backend.data_access.records import PractitionerRecord, UserRecord


class AccountProfileRepository(Protocol):
    async def list_user_ids(self) -> list[str]: ...

    async def list_practitioner_ids(self) -> list[str]: ...

    async def get_user_by_id(self, user_id: str) -> Optional[UserRecord]: ...

    async def get_user_by_email(self, email: str) -> Optional[UserRecord]: ...

    async def save_user(self, user: UserRecord) -> None: ...

    async def get_practitioner_by_id(
        self, practitioner_id: str
    ) -> Optional[PractitionerRecord]: ...

    async def get_practitioner_by_user_id(
        self, user_id: str
    ) -> Optional[PractitionerRecord]: ...

    async def save_practitioner(self, practitioner: PractitionerRecord) -> None: ...
