"""initial relational foundation

Revision ID: 1ee17a60d91c
Revises: 
Create Date: 2026-08-09 12:06:17.381861
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1ee17a60d91c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','active','suspended','closed')", name=op.f('ck_organizations_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('structures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('structure_type', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('accessibility_info', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structures'))
    )
    op.create_index(op.f('ix_structures_city'), 'structures', ['city'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('invited','active','disabled')", name=op.f('ck_users_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('safe_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role_code IN ('organization_admin','coordinator','prescriber','readonly')", name=op.f('ck_organization_members_role_allowed')),
    sa.CheckConstraint("status IN ('invited','active','disabled')", name=op.f('ck_organization_members_status_allowed')),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_organization_members_invited_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('organization_id', 'user_id', name=op.f('uq_organization_members_organization_id'))
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('pilot_accesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('orientation_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_pilot_accesses_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_accesses'))
    )
    op.create_index(op.f('ix_pilot_accesses_organization_id'), 'pilot_accesses', ['organization_id'], unique=False)
    op.create_table('practitioners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('zone', sa.Text(), nullable=False),
    sa.Column('intervention_radius_km', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('indicative_rate', sa.Text(), nullable=False),
    sa.Column('publication_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("publication_status IN ('draft','published','hidden','suspended')", name=op.f('ck_practitioners_publication_status_allowed')),
    sa.CheckConstraint('intervention_radius_km IS NULL OR intervention_radius_km BETWEEN 0 AND 250', name=op.f('ck_practitioners_radius_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_practitioners_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practitioners')),
    sa.UniqueConstraint('user_id', name=op.f('uq_practitioners_user_id'))
    )
    op.create_index(op.f('ix_practitioners_city'), 'practitioners', ['city'], unique=False)
    op.create_table('professional_access_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('requested_role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_professional_access_requests_reviewed_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_professional_access_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_access_requests'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_subscriptions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_roles_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'organization_id', name=op.f('uq_user_roles_user_id'))
    )
    op.create_table('availability_confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('estimated_wait_days', sa.Integer(), nullable=True),
    sa.Column('individual_places', sa.Integer(), nullable=True),
    sa.Column('collective_places', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available','waitlist','unavailable')", name=op.f('ck_availability_confirmations_status_allowed')),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('fk_availability_confirmations_practitioner_id_practitioners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_confirmations')),
    sa.UniqueConstraint('practitioner_id', 'week_start', name=op.f('uq_availability_confirmations_practitioner_id'))
    )
    op.create_index(op.f('ix_availability_confirmations_practitioner_id'), 'availability_confirmations', ['practitioner_id'], unique=False)
    op.create_table('callback_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('phone_encrypted', sa.Text(), nullable=False),
    sa.Column('email_encrypted', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('general_need', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('fk_callback_requests_practitioner_id_practitioners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callback_requests'))
    )
    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('structure_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('fk_classes_practitioner_id_practitioners')),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], name=op.f('fk_classes_structure_id_structures'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes'))
    )
    op.create_index(op.f('ix_classes_practitioner_id'), 'classes', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_classes_session_date'), 'classes', ['session_date'], unique=False)
    op.create_table('diplomas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verified_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending','verified','rejected','expired')", name=op.f('ck_diplomas_verification_status_allowed')),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('fk_diplomas_practitioner_id_practitioners'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_diplomas_verified_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diplomas'))
    )
    op.create_index(op.f('ix_diplomas_practitioner_id'), 'diplomas', ['practitioner_id'], unique=False)
    op.create_table('practitioner_attributes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('attribute_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("attribute_type IN ('audience','modality','experience_domain','accompaniment_type','accompaniment_format','payment_method','habitual_slot')", name=op.f('ck_practitioner_attributes_attribute_type_allowed')),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('fk_practitioner_attributes_practitioner_id_practitioners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practitioner_attributes')),
    sa.UniqueConstraint('practitioner_id', 'attribute_type', 'value', name=op.f('uq_practitioner_attributes_practitioner_id'))
    )
    op.create_index(op.f('ix_practitioner_attributes_practitioner_id'), 'practitioner_attributes', ['practitioner_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_reference', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_practitioner_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('acceptable_radius_km', sa.Integer(), nullable=True),
    sa.Column('general_goal', sa.String(length=120), nullable=False),
    sa.Column('preferred_modality', sa.String(length=64), nullable=False),
    sa.Column('preferred_contact', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created','patient_invited','information_completed','request_sent','practitioner_assigned','patient_contacted','appointment_scheduled','support_started','unsuccessful','cancelled')", name=op.f('ck_referrals_status_allowed')),
    sa.ForeignKeyConstraint(['assigned_practitioner_id'], ['practitioners.id'], name=op.f('fk_referrals_assigned_practitioner_id_practitioners')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_referrals_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_referrals_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('public_reference', name=op.f('uq_referrals_public_reference'))
    )
    op.create_index('ix_referrals_org_status_created', 'referrals', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_referrals_organization_id'), 'referrals', ['organization_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('access_level', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('fk_videos_practitioner_id_practitioners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    op.create_index(op.f('ix_videos_practitioner_id'), 'videos', ['practitioner_id'], unique=False)
    op.create_table('availability_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('confirmation_id', sa.String(length=36), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period IN ('morning','afternoon','evening')", name=op.f('ck_availability_slots_period_allowed')),
    sa.ForeignKeyConstraint(['confirmation_id'], ['availability_confirmations.id'], name=op.f('fk_availability_slots_confirmation_id_availability_confirmations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_slots')),
    sa.UniqueConstraint('confirmation_id', 'slot_date', 'period', name=op.f('uq_availability_slots_confirmation_id'))
    )
    op.create_index(op.f('ix_availability_slots_confirmation_id'), 'availability_slots', ['confirmation_id'], unique=False)
    op.create_table('class_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('cancellation_token_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email_encrypted', sa.Text(), nullable=False),
    sa.Column('phone_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_bookings_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_bookings')),
    sa.UniqueConstraint('cancellation_token_hash', name=op.f('uq_class_bookings_cancellation_token_hash'))
    )
    op.create_index(op.f('ix_class_bookings_class_id'), 'class_bookings', ['class_id'], unique=False)
    op.create_table('professional_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('diploma_id', sa.String(length=36), nullable=True),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','accepted','rejected','deleted')", name=op.f('ck_professional_documents_status_allowed')),
    sa.ForeignKeyConstraint(['diploma_id'], ['diplomas.id'], name=op.f('fk_professional_documents_diploma_id_diplomas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('fk_professional_documents_practitioner_id_practitioners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_documents'))
    )
    op.create_index(op.f('ix_professional_documents_practitioner_id'), 'professional_documents', ['practitioner_id'], unique=False)
    op.create_table('referral_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('refusal_reason', sa.String(length=120), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed','accepted','refused','expired')", name=op.f('ck_referral_assignments_status_allowed')),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], name=op.f('fk_referral_assignments_practitioner_id_practitioners')),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_referral_assignments_referral_id_referrals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_assignments')),
    sa.UniqueConstraint('referral_id', 'practitioner_id', name=op.f('uq_referral_assignments_referral_id'))
    )
    op.create_index(op.f('ix_referral_assignments_referral_id'), 'referral_assignments', ['referral_id'], unique=False)
    op.create_table('referral_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('phone_encrypted', sa.Text(), nullable=False),
    sa.Column('email_encrypted', sa.Text(), nullable=False),
    sa.Column('privacy_notice_version', sa.String(length=40), nullable=False),
    sa.Column('consent_recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_referral_contacts_referral_id_referrals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_contacts')),
    sa.UniqueConstraint('referral_id', name=op.f('uq_referral_contacts_referral_id'))
    )
    op.create_table('referral_patient_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_referral_patient_invitations_referral_id_referrals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_patient_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_referral_patient_invitations_token_hash'))
    )
    op.create_index(op.f('ix_referral_patient_invitations_referral_id'), 'referral_patient_invitations', ['referral_id'], unique=False)
    op.create_table('referral_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('previous_status', sa.String(length=48), nullable=False),
    sa.Column('new_status', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_referral_status_history_actor_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_referral_status_history_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_referral_status_history_referral_id_referrals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_status_history'))
    )
    op.create_index('ix_history_org_occurred', 'referral_status_history', ['organization_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_referral_status_history_organization_id'), 'referral_status_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_referral_status_history_referral_id'), 'referral_status_history', ['referral_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_status_history_referral_id'), table_name='referral_status_history')
    op.drop_index(op.f('ix_referral_status_history_organization_id'), table_name='referral_status_history')
    op.drop_index('ix_history_org_occurred', table_name='referral_status_history')
    op.drop_table('referral_status_history')
    op.drop_index(op.f('ix_referral_patient_invitations_referral_id'), table_name='referral_patient_invitations')
    op.drop_table('referral_patient_invitations')
    op.drop_table('referral_contacts')
    op.drop_index(op.f('ix_referral_assignments_referral_id'), table_name='referral_assignments')
    op.drop_table('referral_assignments')
    op.drop_index(op.f('ix_professional_documents_practitioner_id'), table_name='professional_documents')
    op.drop_table('professional_documents')
    op.drop_index(op.f('ix_class_bookings_class_id'), table_name='class_bookings')
    op.drop_table('class_bookings')
    op.drop_index(op.f('ix_availability_slots_confirmation_id'), table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index(op.f('ix_videos_practitioner_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_referrals_organization_id'), table_name='referrals')
    op.drop_index('ix_referrals_org_status_created', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_practitioner_attributes_practitioner_id'), table_name='practitioner_attributes')
    op.drop_table('practitioner_attributes')
    op.drop_index(op.f('ix_diplomas_practitioner_id'), table_name='diplomas')
    op.drop_table('diplomas')
    op.drop_index(op.f('ix_classes_session_date'), table_name='classes')
    op.drop_index(op.f('ix_classes_practitioner_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_table('callback_requests')
    op.drop_index(op.f('ix_availability_confirmations_practitioner_id'), table_name='availability_confirmations')
    op.drop_table('availability_confirmations')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('professional_access_requests')
    op.drop_index(op.f('ix_practitioners_city'), table_name='practitioners')
    op.drop_table('practitioners')
    op.drop_index(op.f('ix_pilot_accesses_organization_id'), table_name='pilot_accesses')
    op.drop_table('pilot_accesses')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_structures_city'), table_name='structures')
    op.drop_table('structures')
    op.drop_table('roles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
